name: ServerRestartPE
main: iJoshuaHD\iMCPE\ASR\Loader
version: 3.0.0-B1
api: [3.0.0, 3.11.6, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
author: VMPE Development Team
description: Restarts your server at given interval.
website: https://github.com/iJoshuaHD/ASR
commands:
 sr:
  description: "Set ServerRestart Time"
  permission: asr.command.asr
 restart:
  description: "Check ASR Status"
  permission: asr.command.restart
permissions:
 sr.command.sr:
  description: "Usage: /sr <value>"
  default: op
 asr.command.restart:
  description: "Usage: /restart"
  default: op
